### ISSUE TITLE
[ERROR] mailin (ArgumentError) "invalid date"

### ISSUE THREAD

**Issue by garethrees** [mysociety/colombia-theme#22]
```
/data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `eval': invalid date (ArgumentError)
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/fields/resent_date_field.rb:20:in `initialize'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/field.rb:203:in `new'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/field.rb:203:in `new_field'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/field.rb:192:in `create_field'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/field.rb:115:in `initialize'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:93:in `new'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:93:in `block in fields='
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:91:in `each'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:91:in `fields='
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:269:in `split_header'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/header.rb:54:in `initialize'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/message.rb:407:in `new'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/message.rb:407:in `header='
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/message.rb:1972:in `parse_message'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/message.rb:2103:in `init_with_string'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/message.rb:128:in `initialize'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:50:in `new'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/mail-2.5.4/lib/mail/mail.rb:50:in `new'
	from /data/vhost/colombia.alaveteli.org/alaveteli-2021-06-16T12-32-51/lib/mail_handler/backends/mail_backend.rb:44:in `mail_from_raw_email'
	from /data/vhost/colombia.alaveteli.org/alaveteli-2021-06-16T12-32-51/app/mailers/request_mailer.rb:232:in `receive'
	from (eval):1:in `<top (required)>'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `eval'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/commands/runner.rb:54:in `<top (required)>'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/commands.rb:64:in `require'
	from /data/vhost/colombia.alaveteli.org/shared/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.3/lib/rails/commands.rb:64:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by gbp** [comment]
This is due to this header:

`Resent-Date: 7/29/2021 9:17:16 PM`

**Comment by gbp** [comment]
On develop, we can init the Mail object without getting an error. But calling `#resent_date` causes the error:

```ruby
[3] pry(main)> contents = File.read 'foi-mailin-mail-O9esZwG8'
...
[4] pry(main)> Mail.new contents
=> #<Mail::Message:0x4a10>
[5] pry(main)> cd _
...
[7] pry(#<Mail::Message>):1> resent_date
Date::Error: invalid date
from gems/2.7.3p183/gems/mail-2.7.1/lib/mail/fields/resent_date_field.rb:20:in `parse'
[8] pry(#<Mail::Message>):1> date
=> Thu, 29 Jul 2021 16:17:11 -0500
```

**Comment by gbp** [comment]
We don't use `#resent_date` in core so this wouldn't normally be a problem.

**Comment by gbp** [comment]
The mailin script has stopped trying to import this email. So I have manually edited the invalid date to `Resent-Date: Thu, 29 Jul 2021 16:17:16 -0500` and imported

Response is now live:
https://www.queremosdatos.co/request/miembros_de_la_filarmonica#incoming-3348
